Script to test FFT and Filter
v923z/micropython-ulab pull request #241
Opened 2020-11-20 23:25 UTC by mouryarahul

This repo contains the script to test:

1. ulab.convolve

1. ulab.fft.fft

1. ulab.fft.ifft

1. ulab.fft.spectrogram

2020-11-22 19:53 UTC, v923z requested changes

2020-11-22 20:06 UTC, mouryarahul reviewed
I didn't get you. Do you mean we do not need to test `interp` and other functions included in this test?

2020-11-22 20:08 UTC, mouryarahul commented on tests/numpy/filter_fft.py
> +result = (np.convolve(x, y))
Okay, I will separate them.

2020-11-22 20:22 UTC, v923z commented
> I didn't get you. Do you mean we do not need to test `interp` and other functions included in this test?

By my mind, each test should test only a single function, or a set of closely related functions. Even more so that `circuitpython` defines sub-modules, and `interp` and `fft` are not in the same one.

2020-11-22 20:23 UTC, v923z commented on tests/numpy/filter_fft.py
> +result = (np.convolve(x, y))
Thanks!

2020-11-22 20:27 UTC, mouryarahul commented
> > I didn't get you. Do you mean we do not need to test `interp` and other functions included in this test?
> 
> By my mind, each test should test only a single function, or a set of closely related functions. Even more so that `circuitpython` defines sub-modules, and `interp` and `fft` are not in the same one.

@v923z Got it now :). I'll separate them.

2020-11-23 06:45 UTC, merged

2020-11-23 06:45 UTC, v923z commented
@mouryarahul  Thanks for sticking with it will the very end!